
import { Figtree } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import Header from "./(app-components)/Header";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToastProvider from "@/providers/ToasterProvider";
import getSongsByUserId from "@/lib/getSongsByUserId";
import AppSidebar from "./(app-components)/AppSidebar";
import Player from "./(app-components)/Player";

const font = Figtree({subsets : ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const revalidate = 0;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSongs = await getSongsByUserId();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={font.className}
      >
        <ToastProvider/>
        <SupabaseProvider>

          <UserProvider>
           <ModalProvider />
        <SidebarProvider defaultOpen className="object-contain">
          <AppSidebar songs={userSongs}/>
          <main className="w-full h-full  bg-gradient-to-b from-sky-900">
          <Header>
            
        {children}
         </Header>
         <Player/>
        </main>
        </SidebarProvider>
        </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
